---
title: "Final Twitch Time WGCNA"
output: html_notebook
---

```{r}
getwd()
library(WGCNA)
search()
options(stringsAsFactors = FALSE)
TwitchData = read.csv("Final.TwitchTime.genedata.csv")
dim(TwitchData)
names(TwitchData)
datTwitch = as.data.frame(t(TwitchData[, -c(1)]));
names(datTwitch) = TwitchData$Ensembl.ID; 
rownames(datTwitch) = names(TwitchData)[-c(1)];
rownames(datTwitch)
```


```{r}
gsg = goodSamplesGenes(datTwitch, verbose = 3);
gsg$allOK
```


```{r}
sampleTree = hclust(dist(datTwitch), method = "average");
sizeGrWindow(12,9)
par(cex = 0.6);
par(mar = c(0,4,2,0))
plot(sampleTree, main = "Sample clustering to detect outliers", sub="", xlab="", cex.lab = 1.5,
cex.axis = 1.5, cex.main = 2)
```


```{r}
TwitchmuscleData = read.csv("TT MD.csv");
TwitchmuscleData
dim(TwitchmuscleData)
names(TwitchmuscleData)
Twitchmuscles = TwitchmuscleData[, -c(4:9)];
Twitchmuscles = Twitchmuscles[, c(1:3) ];
dim(Twitchmuscles)
names(Twitchmuscles)
TwitchSamples = rownames(datTwitch);
muscleRows = match(TwitchSamples, Twitchmuscles$species);
TwitchMuscles = Twitchmuscles[muscleRows, -1];
rownames(TwitchMuscles) = Twitchmuscles[muscleRows, 1];
collectGarbage();
```


```{r}
sampleTree2 = hclust(dist(datTwitch), method = "average")
muscleColors = numbers2colors(TwitchMuscles, signed = FALSE);
plotDendroAndColors(sampleTree2, muscleColors,
groupLabels = names(TwitchMuscles),
main = "Twitch Gene Expression dendrogram and Muscle Performance heatmap")
```

```{r}
powers = c(c(1:10), seq(from = 12, to=20, by=2))
sft = pickSoftThreshold(datTwitch, powerVector = powers, verbose = 5)
sizeGrWindow(9, 5)
par(mfrow = c(1,2));
cex1 = 0.9;
plot(sft$fitIndices[,1], -sign(sft$fitIndices[,3])*sft$fitIndices[,2],
xlab="Soft Threshold (power)",ylab="Scale Free Topology Model Fit,signed R^2",type="n",
main = paste("Scale independence"));
text(sft$fitIndices[,1], -sign(sft$fitIndices[,3])*sft$fitIndices[,2],
labels=powers,cex=cex1,col="red");
abline(h=0.90,col="red")
plot(sft$fitIndices[,1], sft$fitIndices[,5],
xlab="Soft Threshold (power)",ylab="Mean Connectivity", type="n",
main = paste("Mean connectivity"))
text(sft$fitIndices[,1], sft$fitIndices[,5], labels=powers, cex=cex1,col="red")
```

```{r}
softPower = 9;
adjacency = adjacency(datTwitch, power = softPower);
TOM = TOMsimilarity(adjacency);
dissTOM = 1-TOM
```

```{r}
geneTree = hclust(as.dist(dissTOM), method = "average");
sizeGrWindow(12,9)
plot(geneTree, xlab="", sub="", main = "Gene clustering on TOM-based dissimilarity",
labels = FALSE, hang = 0.04);
```


```{r}
minModuleSize = 65;
dynamicMods = cutreeDynamic(dendro = geneTree, distM = dissTOM,
deepSplit = 2, pamRespectsDendro = FALSE,
minClusterSize = minModuleSize);
table(dynamicMods)
```

```{r}
dynamicColors = labels2colors(dynamicMods)
table(dynamicColors)
sizeGrWindow(8,6)
plotDendroAndColors(geneTree, dynamicColors, "Dynamic Tree Cut",
dendroLabels = FALSE, hang = 0.03,
addGuide = TRUE, guideHang = 0.05,
main = "Gene dendrogram and module colors")
```

```{r}
MEList = moduleEigengenes(datTwitch, colors = dynamicColors)
MEs = MEList$eigengenes
MEDiss = 1-cor(MEs);
METree = hclust(as.dist(MEDiss), method = "average");
sizeGrWindow(7, 6)
plot(METree, main = "Clustering of module eigengenes",
xlab = "", sub = "")
MEDissThres = 0.25
abline(h=MEDissThres, col = "red")
merge = mergeCloseModules(datTwitch, dynamicColors, cutHeight = MEDissThres, verbose = 3)
mergedColors = merge$colors;
mergedMEs = merge$newMEs;
```


```{r}
sizeGrWindow(11, 9)
plotDendroAndColors(geneTree, cbind(mergedColors),
c("Dynamic Tree Cut"),
dendroLabels = FALSE, hang = 0.03,
addGuide = TRUE, guideHang = 0.05)
```


```{r}
moduleColors = mergedColors
colorOrder = c("grey", standardColors(50));
moduleLabels = match(moduleColors, colorOrder)-1;
MEs = MEs;
table(moduleColors)
save(MEs, moduleLabels, moduleColors, geneTree, file = "Twitch-02-networkConstruction-stepByStep.RData")
```

```{r}
nGenes = ncol(datTwitch);
nSamples = nrow(datTwitch);
MEs0 = moduleEigengenes(datTwitch, moduleColors)$eigengenes
MEs = orderMEs(MEs0)
moduleTwitchCor = cor(MEs, TwitchMuscles, use = "p");
moduleTwitchPvalue = corPvalueStudent(moduleTwitchCor, nSamples)
```

```{r}
sizeGrWindow(8,6)
textMatrix = paste(signif(moduleTwitchCor, 2), "\n(",
signif(moduleTwitchPvalue, 1), ")", sep = "");
dim(textMatrix) = dim(moduleTwitchCor)
par(mar = c(6, 8.5, 3, 3));
labeledHeatmap(Matrix = moduleTwitchCor,
xLabels = names(TwitchMuscles),
yLabels = names(MEs),
ySymbols = names(MEs),
colorLabels = FALSE,
colors = blueWhiteRed(50),
textMatrix = textMatrix,
setStdMargins = TRUE,
cex.text = 0.5,
zlim = c(-1,1),
main = paste("Twitch Time Module-Physiology Correlation"))
```


```{r}
Twitch.Time = as.data.frame(TwitchMuscles$Twitch.Time);
names(Twitch.Time) = "Twitch.Time"
modNames = substring(names(MEs), 3)
geneModuleMembership = as.data.frame(cor(datTwitch, MEs, use = "p"));
MMPvalue = as.data.frame(corPvalueStudent(as.matrix(geneModuleMembership), nSamples));
names(geneModuleMembership) = paste("MM", modNames, sep="");
names(MMPvalue) = paste("p.MM", modNames, sep="");
geneMuscleSignificance = as.data.frame(cor(datTwitch, Twitch.Time, use = "p"));
GSPvalue = as.data.frame(corPvalueStudent(as.matrix(geneMuscleSignificance), nSamples));
names(geneMuscleSignificance) = paste("GS.", names(Twitch.Time), sep="");
names(GSPvalue) = paste("p.GS.", names(Twitch.Time), sep="")
```


```{r}
module = "brown"
column = match(module, modNames);
moduleGenes = moduleColors==module;
sizeGrWindow(7, 7);
par(mfrow = c(1,1));
verboseScatterplot(abs(geneModuleMembership[moduleGenes, column]),
abs(geneMuscleSignificance[moduleGenes, 1]),
xlab = paste("Module Membership in", module, "module"),
ylab = "Gene significance for Specific Tension",
main = paste("Module membership vs. gene significance\n"),
cex.main = 1.2, cex.lab = 1.2, cex.axis = 1.2, col = module)
names(datTwitch)[moduleColors=="brown"]
```


```{r}
#names(datTwitch)[moduleColors1=="green"]
annot = read.csv(file = "Final Twitch Time Annotation.csv");
dim(annot)
names(annot)
Twitchprobes = names(datTwitch)
probes2annot = match(Twitchprobes, annot$Ensembl.ID) 
sum(is.na(probes2annot))
```


```{r}
geneInfo0 = data.frame(Ensembl.ID = Twitchprobes,
geneSymbol = annot$Gene.Name[probes2annot],
EntrezID = annot$Ensembl.ID2[probes2annot],
moduleColor = moduleColors,
geneMuscleSignificance,
GSPvalue);
moduleColors
modOrder = order(-abs(cor(MEs, Twitch.Time, use = "p")));
for (mod in 1:ncol(geneModuleMembership))
{
  oldNames = names(geneInfo0)
  geneInfo0 = data.frame(geneInfo0, geneModuleMembership[, modOrder[mod]],
MMPvalue[, modOrder[mod]]);
  names(geneInfo0) = c(oldNames, paste("MM.", modNames[modOrder[mod]], sep=""),
paste("p.MM.", modNames[modOrder[mod]], sep=""))
}
geneOrder = order(geneInfo0$moduleColor, -abs(geneInfo0$GS.Twitch.Time));
geneInfo = geneInfo0[geneOrder, ]
write.csv(geneInfo, file = "Twitch gene Info.csv")
```


```{r}
annot1 = read.csv(file = "Final Twitch Time Annotation.csv");
Twitchprobes = names(datTwitch)
probes2annot1 = match(Twitchprobes, annot1$Ensembl.ID)
TwitchEntrez = annot1$Ensembl.ID2[probes2annot1];
intModules = c("black", "red", "pink", "green", "turquoise", "blue", "brown")
for (module in intModules)
{
  modGenes = (moduleColors==module)
  modEntrez = TwitchEntrez[modGenes];
  modEntrez
  fileName = paste("Final Twitch Time Module", module, ".txt", sep="");
  write.table(as.data.frame(modEntrez), file = fileName,
              row.names = FALSE, col.names = FALSE)
}
fileName = paste("Final Twitch Time Background.txt", sep="");
write.table(as.data.frame(TwitchEntrez), file = fileName,
            row.names = FALSE, col.names = FALSE)
```

